apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [
          {
            "resourceName": "hca_shared_devices_a",
            "rdmaHcaMax": 1000,
            "selectors": {
              "ifNames": ["eno49np0", "eno50np1"]
            }
          },
          {
            "resourceName": "hca_shared_devices_b",
            "rdmaHcaMax": 500,
            "selectors": {
              "ifNames": ["ens1f0np0", "ens1f1np1"]
            }
          }
        ]
    }
